export declare global {
  type TranslateKeys =
    | 'about'
    | 'blog'
    | 'booking-filters'
    | 'breadcrumbs'
    | 'cart'
    | 'checkout'
    | 'chefs-details'
    | 'chefs-store-details'
    | 'chefs-store'
    | 'chefs-table'
    | 'chefs'
    | 'chip'
    | 'choose-date'
    | 'faq'
    | 'footer'
    | 'header'
    | 'main-navigation'
    | 'main-search'
    | 'main'
    | 'masterclass-details'
    | 'masterclasses'
    | 'menu'
    | 'pagination'
    | 'product-details'
    | 'product-info-sidebar'
    | 'products-filter'
    | 'profile'
    | 'rating-filter'
    | 'recipes-details'
    | 'recipes'
    | 'reset-password'
    | 'search'
    | 'sort-by'
    | 'validation';
}
