import { OptionVariants, StatusEnum, Supplier } from 'services/types';

export default {
  queryString: 'cuisine_ids=2&chef_ids=7,6,5&minPrice=6900&maxPrice=15000&take=50',
  queryObject: {
    cuisine_ids: 2,
    chef_ids: [7, 6, 5],
    minPrice: 6900,
    maxPrice: 15000,
    take: 50,
  },
  variations: [
    {
      id: 109,
      slug: 'colors',
      name: 'Colors',
      description: '',
      type: 'color',
      selectColor: false,
      status: 'active',
      options: [
        { id: 370, name: 'Red', slug: null, price: 100, multiplier: 1, color: '#e82e2e' },
        { id: 373, name: 'Blue', slug: null, price: 100, multiplier: 1, color: '#1d3bab' },
        { id: 372, name: 'Green', slug: null, price: 100, multiplier: 1, color: '#26d268' },
        { id: 371, name: 'Black', slug: null, price: 100, multiplier: 1, color: '#220707' },
      ],
      supplier: {
        id: '65',
        slug: 'Casinetto',
        name: 'Casinetto',
        description:
          'Founded in 2009, Casinetto is a provider of only high-quality, sustainably-produced, and authentic Italian foods that come with an untarnished reputation and generations of experience.',
        image: 'http://files.unknown.me/image/65cf0bbb-0128-4590-aa7a-d09015149ec1.png',
        company: {
          name: 'Casinetto',
          type: 'Store',
          image: 'http://files.unknown.me/image/65cf0bbb-0128-4590-aa7a-d09015149ec1.png',
          description:
            'Founded in 2009, Casinetto is a provider of only high-quality, sustainably-produced, and authentic Italian foods that come with an untarnished reputation and generations of experience.',
        },
        locationInfo: {
          lat: '25.2073',
          area: { code: 'jumeirah-park', name: 'Jumeirah Park' },
          city: { code: 'dubai', name: 'Dubai' },
          long: '55.2587',
          notes: 'Please call us',
          street: '123',
          buildingNumber: '1234',
        },
        contactInfo: {
          name: 'Bassel Siblini',
          email: 'casinetto@unknown.me',
          links: ['https://www.casinetto.com'],
          phone: '056544412245616',
        },
        type: 'supplier',
        createdAt: '2021-05-18T05:43:39.871Z',
        updatedAt: '2021-05-20T11:37:32.202Z',
        deletedAt: null,
        status: 'active',
      },
      items: '0',
    },
    {
      id: 104,
      slug: 'Color-01',
      name: 'Color 01',
      description: 'testtt',
      type: 'color',
      selectColor: false,
      status: 'active',
      options: [
        { id: 367, name: 'red', slug: null, price: 100, multiplier: 1, color: '#b62323' },
        { id: 368, name: 'eeee', slug: null, price: 120, multiplier: 1, color: '#8b2b2b' },
        { id: 369, name: 'blue', slug: null, price: 100, multiplier: 1, color: '#0c0c19' },
      ],
      supplier: {
        id: '65',
        slug: 'Casinetto',
        name: 'Casinetto',
        description:
          'Founded in 2009, Casinetto is a provider of only high-quality, sustainably-produced, and authentic Italian foods that come with an untarnished reputation and generations of experience.',
        image: 'http://files.unknown.me/image/65cf0bbb-0128-4590-aa7a-d09015149ec1.png',
        company: {
          name: 'Casinetto',
          type: 'Store',
          image: 'http://files.unknown.me/image/65cf0bbb-0128-4590-aa7a-d09015149ec1.png',
          description:
            'Founded in 2009, Casinetto is a provider of only high-quality, sustainably-produced, and authentic Italian foods that come with an untarnished reputation and generations of experience.',
        },
        locationInfo: {
          lat: '25.2073',
          area: { code: 'jumeirah-park', name: 'Jumeirah Park' },
          city: { code: 'dubai', name: 'Dubai' },
          long: '55.2587',
          notes: 'Please call us',
          street: '123',
          buildingNumber: '1234',
        },
        contactInfo: {
          name: 'Bassel Siblini',
          email: 'casinetto@unknown.me',
          links: ['https://www.casinetto.com'],
          phone: '056544412245616',
        },
        type: 'supplier',
        createdAt: '2021-05-18T05:43:39.871Z',
        updatedAt: '2021-05-20T11:37:32.202Z',
        deletedAt: null,
        status: 'active',
      },
      items: '0',
    },
    {
      id: 97,
      slug: 'size',
      name: 'Size',
      description: '',
      type: 'size',
      selectColor: false,
      status: 'active',
      options: [
        { id: 346, name: 'Small', slug: null, price: 10, multiplier: 1, color: null },
        { id: 347, name: 'Medium ', slug: null, price: 15, multiplier: 1, color: null },
        { id: 348, name: 'Large', slug: null, price: 25, multiplier: 1, color: null },
      ],
      supplier: {
        id: '65',
        slug: 'Casinetto',
        name: 'Casinetto',
        description:
          'Founded in 2009, Casinetto is a provider of only high-quality, sustainably-produced, and authentic Italian foods that come with an untarnished reputation and generations of experience.',
        image: 'http://files.unknown.me/image/65cf0bbb-0128-4590-aa7a-d09015149ec1.png',
        company: {
          name: 'Casinetto',
          type: 'Store',
          image: 'http://files.unknown.me/image/65cf0bbb-0128-4590-aa7a-d09015149ec1.png',
          description:
            'Founded in 2009, Casinetto is a provider of only high-quality, sustainably-produced, and authentic Italian foods that come with an untarnished reputation and generations of experience.',
        },
        locationInfo: {
          lat: '25.2073',
          area: { code: 'jumeirah-park', name: 'Jumeirah Park' },
          city: { code: 'dubai', name: 'Dubai' },
          long: '55.2587',
          notes: 'Please call us',
          street: '123',
          buildingNumber: '1234',
        },
        contactInfo: {
          name: 'Bassel Siblini',
          email: 'casinetto@unknown.me',
          links: ['https://www.casinetto.com'],
          phone: '056544412245616',
        },
        type: 'supplier',
        createdAt: '2021-05-18T05:43:39.871Z',
        updatedAt: '2021-05-20T11:37:32.202Z',
        deletedAt: null,
        status: 'active',
      },
      items: '0',
    },
    {
      id: 90,
      slug: 'weight',
      name: 'Weight',
      description: 'Weight difference',
      type: 'size',
      selectColor: false,
      status: 'active',
      options: [
        { id: 320, name: '200grs', slug: null, price: 50, multiplier: 1, color: null },
        { id: 323, name: '1 KG', slug: null, price: 139, multiplier: 1, color: null },
        { id: 322, name: '500grs', slug: null, price: 89, multiplier: 1, color: null },
        { id: 321, name: '300grs', slug: null, price: 70, multiplier: 1, color: null },
      ],
      supplier: {
        id: '65',
        slug: 'Casinetto',
        name: 'Casinetto',
        description:
          'Founded in 2009, Casinetto is a provider of only high-quality, sustainably-produced, and authentic Italian foods that come with an untarnished reputation and generations of experience.',
        image: 'http://files.unknown.me/image/65cf0bbb-0128-4590-aa7a-d09015149ec1.png',
        company: {
          name: 'Casinetto',
          type: 'Store',
          image: 'http://files.unknown.me/image/65cf0bbb-0128-4590-aa7a-d09015149ec1.png',
          description:
            'Founded in 2009, Casinetto is a provider of only high-quality, sustainably-produced, and authentic Italian foods that come with an untarnished reputation and generations of experience.',
        },
        locationInfo: {
          lat: '25.2073',
          area: { code: 'jumeirah-park', name: 'Jumeirah Park' },
          city: { code: 'dubai', name: 'Dubai' },
          long: '55.2587',
          notes: 'Please call us',
          street: '123',
          buildingNumber: '1234',
        },
        contactInfo: {
          name: 'Bassel Siblini',
          email: 'casinetto@unknown.me',
          links: ['https://www.casinetto.com'],
          phone: '056544412245616',
        },
        type: 'supplier',
        createdAt: '2021-05-18T05:43:39.871Z',
        updatedAt: '2021-05-20T11:37:32.202Z',
        deletedAt: null,
        status: 'active',
      },
      items: '0',
    },
  ],
  cart: {
    id: 155,
    session: '7O1W-4wAjRAU9jFXXAO_8',
    total: 1185,
    status: null,
    products: [
      {
        id: '255',
        quantity: 4,
        name: 'Alba Tart (3 pieces)',
        image: 'https://files.unknown.me/image/ef9f03b7-9c66-412c-a880-02b9dd4180aa.jpeg',
        price: '540.00',
        oldPrice: null,
        options: [],
        createdAt: '2021-08-12T16:58:35.208Z',
        updatedAt: '2021-08-12T16:58:35.608Z',
        deletedAt: null,
        product: {
          id: '407',
          slug: 'alba-tart-(3-pieces)',
          name: 'Alba Tart (3 pieces)',
          description: "karim's interpretation of the Alba tart.\nExplosion of Hazelnut Praline.",
          shortDescription: null,
          sku: null,
          price: '135.00',
          supplierPrice: '114.00',
          chefPrice: '0.00',
          msrpPrice: '0.00',
          instruction: null,
          type: 'menu',
          time: null,
          rating: 0,
          inventory: null,
          isFree: false,
          status: 'active',
          createdAt: '2021-08-05T07:19:15.212Z',
          updatedAt: '2021-08-05T07:19:15.212Z',
          deletedAt: null,
          supplier: {
            id: '11',
            slug: 'Kayu-The-Lab',
            name: 'Kayu The Lab',
            description: "Karim bourgi's kitchen",
            image: 'https://files.unknown.me/image/cdd1fc64-43d6-4a22-a7fe-0300e0502552.png',
            company: {
              name: 'Kayu The Lab',
              type: 'supplier',
              image: 'https://files.beta.unknown.me/image/cdd1fc64-43d6-4a22-a7fe-0300e0502552.png',
              description: "Karim bourgi's kitchen",
            },
            locationInfo: {
              lat: '25.1571',
              area: { code: 'maydan-nad-al-sheba-1', name: 'Maydan / Nad Al Sheba 1' },
              city: { code: 'dubai', name: 'Dubai' },
              long: '55.2646',
              notes: '11',
              street: 'Nad el sheba 1',
              building: 'Manazel nad el sheba residence 1',
              apartment: '1',
            },
            contactInfo: {
              name: 'Karim bourji',
              email: 'info@kayuthelab.com',
              links: ['https://trykayu.com'],
              phone: '97150-775-9818',
            },
            type: 'cloud-kitchen',
            createdAt: '2021-07-27T12:07:40.354Z',
            updatedAt: '2021-07-27T12:11:25.634Z',
            deletedAt: null,
            status: 'active',
          },
        },
      },
      {
        id: '256',
        quantity: 1,
        name: 'Almafi Lemon (3 pieces)',
        image: 'https://files.unknown.me/image/755096fe-b175-46d0-8e4d-337bf7ce4470.jpeg',
        price: '135.00',
        oldPrice: null,
        options: [],
        createdAt: '2021-08-12T16:58:36.116Z',
        updatedAt: '2021-08-12T16:58:36.116Z',
        deletedAt: null,
        product: {
          id: '405',
          slug: 'almafi-lemon-(3-pieces)',
          name: 'Almafi Lemon (3 pieces)',
          description: 'Named after the beautiful Italian coast known for its wonderful lemon-based desserts.',
          shortDescription: null,
          sku: null,
          price: '135.00',
          supplierPrice: '114.50',
          chefPrice: '0.00',
          msrpPrice: '0.00',
          instruction: null,
          type: 'menu',
          time: null,
          rating: 0,
          inventory: null,
          isFree: false,
          status: 'active',
          createdAt: '2021-08-05T07:15:05.732Z',
          updatedAt: '2021-08-05T07:15:05.732Z',
          deletedAt: null,
          supplier: {
            id: '11',
            slug: 'Kayu-The-Lab',
            name: 'Kayu The Lab',
            description: "Karim bourgi's kitchen",
            image: 'https://files.unknown.me/image/cdd1fc64-43d6-4a22-a7fe-0300e0502552.png',
            company: {
              name: 'Kayu The Lab',
              type: 'supplier',
              image: 'https://files.beta.unknown.me/image/cdd1fc64-43d6-4a22-a7fe-0300e0502552.png',
              description: "Karim bourgi's kitchen",
            },
            locationInfo: {
              lat: '25.1571',
              area: { code: 'maydan-nad-al-sheba-1', name: 'Maydan / Nad Al Sheba 1' },
              city: { code: 'dubai', name: 'Dubai' },
              long: '55.2646',
              notes: '11',
              street: 'Nad el sheba 1',
              building: 'Manazel nad el sheba residence 1',
              apartment: '1',
            },
            contactInfo: {
              name: 'Karim bourji',
              email: 'info@kayuthelab.com',
              links: ['https://trykayu.com'],
              phone: '97150-775-9818',
            },
            type: 'cloud-kitchen',
            createdAt: '2021-07-27T12:07:40.354Z',
            updatedAt: '2021-07-27T12:11:25.634Z',
            deletedAt: null,
            status: 'active',
          },
        },
      },
      {
        id: '257',
        quantity: 1,
        name: 'Mango Roll (3 pieces)',
        image: 'https://files.unknown.me/image/9af08fec-cfcc-4bcd-b3de-36e11d42b9bd.jpeg',
        price: '135.00',
        oldPrice: null,
        options: [],
        createdAt: '2021-08-12T16:58:36.740Z',
        updatedAt: '2021-08-12T16:58:36.740Z',
        deletedAt: null,
        product: {
          id: '403',
          slug: 'mango-roll-(3-pieces)',
          name: 'Mango Roll (3 pieces)',
          description: 'Summer Freshness. \nA must-try for all mango lovers out there.',
          shortDescription: null,
          sku: null,
          price: '135.00',
          supplierPrice: '114.75',
          chefPrice: '0.00',
          msrpPrice: '0.00',
          instruction: null,
          type: 'menu',
          time: null,
          rating: 0,
          inventory: null,
          isFree: false,
          status: 'active',
          createdAt: '2021-08-05T07:12:06.407Z',
          updatedAt: '2021-08-05T07:12:06.407Z',
          deletedAt: null,
          supplier: {
            id: '11',
            slug: 'Kayu-The-Lab',
            name: 'Kayu The Lab',
            description: "Karim bourgi's kitchen",
            image: 'https://files.unknown.me/image/cdd1fc64-43d6-4a22-a7fe-0300e0502552.png',
            company: {
              name: 'Kayu The Lab',
              type: 'supplier',
              image: 'https://files.beta.unknown.me/image/cdd1fc64-43d6-4a22-a7fe-0300e0502552.png',
              description: "Karim bourgi's kitchen",
            },
            locationInfo: {
              lat: '25.1571',
              area: { code: 'maydan-nad-al-sheba-1', name: 'Maydan / Nad Al Sheba 1' },
              city: { code: 'dubai', name: 'Dubai' },
              long: '55.2646',
              notes: '11',
              street: 'Nad el sheba 1',
              building: 'Manazel nad el sheba residence 1',
              apartment: '1',
            },
            contactInfo: {
              name: 'Karim bourji',
              email: 'info@kayuthelab.com',
              links: ['https://trykayu.com'],
              phone: '97150-775-9818',
            },
            type: 'cloud-kitchen',
            createdAt: '2021-07-27T12:07:40.354Z',
            updatedAt: '2021-07-27T12:11:25.634Z',
            deletedAt: null,
            status: 'active',
          },
        },
      },
      {
        id: '258',
        quantity: 5,
        name: 'Croissant Beurre (3 pieces)',
        image: 'https://files.unknown.me/image/f92cf0c1-32ad-4e9f-b387-ae00280ea935.jpeg',
        price: '375.00',
        oldPrice: null,
        options: [],
        createdAt: '2021-08-12T16:58:37.435Z',
        updatedAt: '2021-08-12T16:58:38.029Z',
        deletedAt: null,
        product: {
          id: '408',
          slug: 'croissant-beurre-(3-pieces)',
          name: 'Croissant Beurre (3 pieces)',
          description: 'Plain butter croissant',
          shortDescription: null,
          sku: null,
          price: '75.00',
          supplierPrice: '63.70',
          chefPrice: '0.00',
          msrpPrice: '0.00',
          instruction: null,
          type: 'menu',
          time: null,
          rating: 0,
          inventory: null,
          isFree: false,
          status: 'active',
          createdAt: '2021-08-05T07:25:06.342Z',
          updatedAt: '2021-08-05T07:25:06.342Z',
          deletedAt: null,
          supplier: {
            id: '11',
            slug: 'Kayu-The-Lab',
            name: 'Kayu The Lab',
            description: "Karim bourgi's kitchen",
            image: 'https://files.unknown.me/image/cdd1fc64-43d6-4a22-a7fe-0300e0502552.png',
            company: {
              name: 'Kayu The Lab',
              type: 'supplier',
              image: 'https://files.beta.unknown.me/image/cdd1fc64-43d6-4a22-a7fe-0300e0502552.png',
              description: "Karim bourgi's kitchen",
            },
            locationInfo: {
              lat: '25.1571',
              area: { code: 'maydan-nad-al-sheba-1', name: 'Maydan / Nad Al Sheba 1' },
              city: { code: 'dubai', name: 'Dubai' },
              long: '55.2646',
              notes: '11',
              street: 'Nad el sheba 1',
              building: 'Manazel nad el sheba residence 1',
              apartment: '1',
            },
            contactInfo: {
              name: 'Karim bourji',
              email: 'info@kayuthelab.com',
              links: ['https://trykayu.com'],
              phone: '97150-775-9818',
            },
            type: 'cloud-kitchen',
            createdAt: '2021-07-27T12:07:40.354Z',
            updatedAt: '2021-07-27T12:11:25.634Z',
            deletedAt: null,
            status: 'active',
          },
        },
      },
    ],
  },
  addresses: [
    {
      id: 199,
      street: 'Ddf',
      building: '10',
      lat: '31.4083',
      lng: '34.4147',
      apartment: '200',
      notes: '',
      images: ['https://files.dev.unknown.me/image/709229c8-2a55-4537-86c4-6a692a2f6ffb.jpeg'],
      city: { code: 'dubai', name: 'Dubai', createdAt: '2021-03-16T11:47:09.170Z', deletedAt: null },
      area: { code: 'jumeirah-park', name: 'Jumeirah Park', cityCode: 'dubai' },
      chef: {
        id: '54',
        slug: 'chef-salwa-c9pvyf',
        name: 'Salwa',
        email: 'chef.salwa765@gmail.com',
        description:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        image: 'https://files.dev.unknown.me/image/5bc84ac2-d8d6-4842-a861-64ff5ece5763.jpeg',
        jobRole: 'Chaf @ Royal catering Company',
        isActive: true,
        links: ['https://test.me/twitter', 'https://test.com/facebook', 'https://test.com/instagram'],
        createdAt: '2021-08-02T11:35:18.368Z',
        updatedAt: '2021-08-12T11:33:30.565Z',
        deletedAt: null,
        status: 'active',
        cover: 'https://files.dev.unknown.me/image/4fb62284-0ade-4e20-bb45-7b75e6021247.jpeg',
      },
    },
    {
      id: 198,
      street: 'Level P3 Commercial',
      building: 'Office Building',
      lat: '31.5067',
      lng: '34.4565',
      apartment: 'Central Park Towers flat',
      notes: 'Central Park Towers - Level P3 Commercial - Office Building',
      images: ['http://files.unknown.me/image/5215c6c0-1347-490c-850d-ebeb85356dd3.png'],
      city: { code: 'dubai', name: 'Dubai', createdAt: '2021-03-16T11:47:09.170Z', deletedAt: null },
      area: { code: 'internet-city', name: 'Internet City', cityCode: 'dubai' },
      chef: null,
    },
    {
      id: 197,
      street: 'Level P3 Commercial',
      building: 'Office Building',
      lat: '31.5067',
      lng: '34.4565',
      apartment: 'Central Park Towers flat',
      notes: 'Central Park Towers - Level P3 Commercial - Office Building',
      images: ['http://files.unknown.me/image/5215c6c0-1347-490c-850d-ebeb85356dd3.png'],
      city: { code: 'dubai', name: 'Dubai', createdAt: '2021-03-16T11:47:09.170Z', deletedAt: null },
      area: { code: 'internet-city', name: 'Internet City', cityCode: 'dubai' },
      chef: null,
    },
    {
      id: 196,
      street: 'Level P3 Commercial',
      building: 'Office Building',
      lat: '25.2684',
      lng: '55.2962',
      apartment: 'Central Park Towers flat',
      notes: 'Central Park Towers - Level P3 Commercial - Office Building',
      images: ['http://files.unknown.me/image/5215c6c0-1347-490c-850d-ebeb85356dd3.png'],
      city: { code: 'dubai', name: 'Dubai', createdAt: '2021-03-16T11:47:09.170Z', deletedAt: null },
      area: { code: 'internet-city', name: 'Internet City', cityCode: 'dubai' },
      chef: null,
    },
    {
      id: 195,
      street: 'Level P3 Commercial',
      building: 'Office Building',
      lat: '29.4687',
      lng: '116.3086',
      apartment: 'Central Park Towers flat',
      notes: 'Central Park Towers - Level P3 Commercial - Office Building',
      images: ['http://files.unknown.me/image/5215c6c0-1347-490c-850d-ebeb85356dd3.png'],
      city: { code: 'dubai', name: 'Dubai', createdAt: '2021-03-16T11:47:09.170Z', deletedAt: null },
      area: { code: 'internet-city', name: 'Internet City', cityCode: 'dubai' },
      chef: null,
    },
    {
      id: 194,
      street: 'Marina Street',
      building: '44',
      lat: '43.2594',
      lng: '44.7661',
      apartment: '78ии',
      notes: 'Notesssssssssssss',
      images: ['https://files.dev.unknown.me/image/5609405b-044d-42b0-9dc5-9c6d90bc0ef3.jpeg'],
      city: { code: 'dubai', name: 'Dubai', createdAt: '2021-03-16T11:47:09.170Z', deletedAt: null },
      area: { code: 'marina', name: 'Marina', cityCode: 'dubai' },
      chef: {
        id: '31',
        slug: 'ali-loremipsum-q9p6n',
        name: 'Faisal Naser',
        email: 'webdevelali@gmail.com',
        description:
          'Chef Faisal is a young Emirati Chef widely known for his Instagram educational food content. His restaurant Lento, attracts followers from all across the UAE. \n',
        image: 'http://files.unknown.me/image/1be79a19-81c3-4cba-a7ad-3d640af5785f.jpeg',
        jobRole: 'Chef Owner @ Lento ',
        isActive: true,
        links: ['https://www.instagram.com/fai.s.a.l/?hl=en'],
        createdAt: '2021-04-23T07:38:28.563Z',
        updatedAt: '2021-07-31T09:02:31.322Z',
        deletedAt: null,
        status: 'active',
        cover: 'http://files.unknown.me/image/347032d9-434d-4f7a-b2a2-fc78d4b7d7bb.jpeg',
      },
    },
    {
      id: 193,
      street: 'Level P3 Commercial',
      building: 'Office Building',
      lat: '31.529369599999995',
      lng: '34.465382399999996',
      apartment: 'Central Park Towers flat',
      notes: 'Central Park Towers - Level P3 Commercial - Office Building',
      images: ['http://files.unknown.me/image/5215c6c0-1347-490c-850d-ebeb85356dd3.png'],
      city: { code: 'dubai', name: 'Dubai', createdAt: '2021-03-16T11:47:09.170Z', deletedAt: null },
      area: { code: 'internet-city', name: 'Internet City', cityCode: 'dubai' },
      chef: null,
    },
    {
      id: 192,
      street: 'Level P3 Commercial ',
      building: 'Office Building',
      lat: '31.512985599999997',
      long: '34.4588288',
      apartment: 'Central Park Towers',
      notes: 'Central Park Towers - Level P3 Commercial - Office Building',
      images: [
        'http://files.unknown.me/image/5215c6c0-1347-490c-850d-ebeb85356dd3.png',
        'blob:https://dev.unknown.me/d3487c21-ef70-4501-8111-2e31b3f78ca4',
      ],
      city: { code: 'dubai', name: 'Dubai', createdAt: '2021-03-16T11:47:09.170Z', deletedAt: null },
      area: { code: 'al-furjan-villas', name: 'Al Furjan Villas', cityCode: 'dubai' },
      chef: null,
    },
    {
      id: 191,
      street: 'str',
      building: '82746823',
      lat: '31.512985599999997',
      lng: '34.4588288',
      apartment: '4444',
      notes: '',
      images: ['https://files.dev.unknown.me/image/ae78a928-d0e5-4e00-95a4-af312411ce54.png'],
      city: { code: 'dubai', name: 'Dubai', createdAt: '2021-03-16T11:47:09.170Z', deletedAt: null },
      area: { code: 'the-gardens', name: 'The Gardens', cityCode: 'dubai' },
      chef: null,
    },
    {
      id: 188,
      street: 'Level P3 Commercial ',
      building: 'Office Building',
      lat: '31.512985599999997',
      lng: '34.4588288',
      apartment: 'Central Park Towers',
      notes: 'Central Park Towers - Level P3 Commercial - Office Building',
      images: [
        'http://files.unknown.me/image/5215c6c0-1347-490c-850d-ebeb85356dd3.png',
        'blob:https://dev.unknown.me/d3487c21-ef70-4501-8111-2e31b3f78ca4',
      ],
      city: { code: 'dubai', name: 'Dubai', createdAt: '2021-03-16T11:47:09.170Z', deletedAt: null },
      area: { code: 'al-furjan-villas', name: 'Al Furjan Villas', cityCode: 'dubai' },
      chef: null,
    },
  ],
};
